#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
MAIN="$DIR"
set +e

source "$DIR/src/config"
source "$SRC/scheduling"
source "$SRC/publish"
source "$SRC/export"

echo "Pulling last repository version"
git pull

determine_scheduled

echo "Exporting commits for $scheduled_formatted"
export_projects "$scheduled_formatted"
echo "Publishing for $scheduled"
publish "$scheduled" "$scheduled_year"

remember_last_export
